### ISSUE TITLE
Esphome 12.2022 & HA - MBUS: Start bytes do not match & Frame too big for received data

### ISSUE THREAD

**Issue by flo-dl** [DomiStyle/esphome-dlms-meter#19]
Hey all,
the code and hardware was working great for me the last few months (thanks for that btw!) but the recent 12.2022 Esphome upgrade, which I run as a Home Assistant add-on, seems to have broken something. I have the Kaifa MA110M smart meter (IKB).

As others, I'm using a m-bus-slave-click for the connection to the smart meter. I have a DFRobot FireBeetle 2 ESP32-E IoT Microcontroller board (this one: https://www.dfrobot.com/product-2231.html) because of it's low energy consumption in deep sleep as all parts are powered by a battery.

So, I updated the Esphome add-on to 12.2022 today and also pushed the available update to the devices. After those updates were done, I now get the following two error messages in the Esphome log of my board:

[15:05:16][E][espdm:048]: MBUS: Start bytes do not match
[15:05:16][E][espdm:064]: MBUS: Frame too big for received data

My uart configuration is:
```
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 2400
  rx_buffer_size: 1024 # Needed to receive the large packets send by the smart meter
  id: mbus
```

I've tried adjusting the `rx_buffer_size` to 2048 and also tried other things that were mentioned in other issues (i.e. adding parity, data and stop bits) but that didn't do the trick.

So, does anybody have an idea what might have changed or how I go about debugging it?
Thanks in advance, and I hope I've provided enough information.

**Comment by DomiStyle** [comment]
I can reproduce this on 2022.12 but I'm gonna have to check what changed.

For now, 2022.11.5 works fine.

**Comment by theexit** [comment]
I had also an issue since update to 12.2022.
[13:23:12][E][espdm:038]: Received packet with invalid size
[13:23:12][E][espdm:038]: Received packet with invalid size
[13:23:13][E][espdm:038]: Received packet with invalid size
Hope this helps a little bit.

**Comment by theexit** [comment]
#21 added fix... is working for me!

**Comment by flo-dl** [comment]
> #21 added fix... is working for me!

Thanks a lot to the both of you. It wouldn't work for me (IKB) with just adding the delay. While the "Frame too big for received data" didn't show up in the log anymore, the "Start bytes do not match" was still there. I had to change my uart config from:
```
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 2400
  rx_buffer_size: 1024 # Needed to receive the large packets send by the smart meter
  id: mbus
```
to
```
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 2400
  parity: EVEN
  data_bits: 8
  stop_bits: 1
  rx_buffer_size: 2048
  id: mbus
```
I haven't checked what actually made the difference, but the above-mentioned fix and this config change worked in my case.
