### ISSUE TITLE
Tinetz Honeywell funktioniert -> Achtung Anzahl der Stellen

### ISSUE THREAD

**Issue by ert666** [DomiStyle/esphome-dlms-meter#37]
Hallo,
Tinetz Honeywell for customers with PV works after some try & error with UART.
There is a 16 digit key so don´t forget to expand the uint8_key and set the key to 16

      uint8_t key[] = {0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0x00, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16};
      dlms_meter->set_key(key, **16**); // Pass your decryption key and key length here

THX!

**Comment by ert666** [comment]
I get about 10+ bad values per day that are way too high.
There are different threads about that and the Log says:

> [20:35:26][E][espdm:200]: OBIS: Unsupported OBIS header length

I added filters to all platform templates so the bad values don´t reach HASSIO

i.e.
```
  - platform: template
    id: meter01_active_power_plus
    name: meter01_active_power_plus
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: "power"
    state_class: "measurement"
    filters:
      - median:
          window_size: 7
          send_every: 4
```

<img width="1469" alt="Screenshot 2024-02-08 203941" src="https://github.com/DomiStyle/esphome-dlms-meter/assets/16924811/e059a1b7-da8e-4baf-a1f1-87cc10239e6c">
