### ISSUE TITLE
Bug since esphome 2025-02: "custom" component has been removed

### ISSUE THREAD

**Issue by pos-ei-don** [DomiStyle/esphome-dlms-meter#47]
```
Failed config

custom_component: [source /config/esphome/smartmeter-esp.yaml:307]
  
  The "custom" component has been removed. Consider conversion to an external component.
  https://esphome.io/guides/contributing#a-note-about-custom-components.
  - lambda: |-
      
      auto dlms_meter = new esphome::espdm::DlmsMeter(id(mbus));
      
      uint8_t key[] = {};
      dlms_meter->set_key(key, 16); // Pass your decryption key and key length here
      
      dlms_meter->set_voltage_sensors(id(meter01_voltage_l1), id(meter01_voltage_l2), id(meter01_voltage_l3)); // Set sensors to use for voltage (optional)
      
      dlms_meter->set_current_sensors(id(meter01_current_l1), id(meter01_current_l2), id(meter01_current_l3)); // Set sensors to use for current (optional)
      
```

Can anyone update the tescription to use it as external component?

**Comment by cococheaf** [comment]
The problem is that the ESP Home custom_component was replaced by the external_component.

Here is a link to the announcement of the removal:
https://esphome.io/guides/contributing#a-note-about-custom-components

And here is the link to the external component documentation:
https://esphome.io/components/external_components

@DomiStyle - can you please check the code and rewrite?
Thank you - greeting aus Höchst ;)

**Comment by pos-ei-don** [comment]
Just saw that a fork of this project did this, unfortunately they
also changed the code to support only a certain type of smartmeter.
So I cannot use this code.

Here is a Reference to the other code, maybe it helps to update this code? 
Or maybe @mariopenzendorfer can provide a PR for this?
https://github.com/mariopenzendorfer/esphome-smartmeter/commit/36bee98c26d75a35417d0856a789496d9c340935

**Comment by ximex** [comment]
maybe this PR helps someone: https://github.com/esphome/esphome/pull/8009
```yaml
external_components:
  - source: github://pr#8009
    components: [ dlms_meter ]
```

Edit: fixed to copy/past errors

**Comment by cococheaf** [comment]
I am testing it right now, as for now it seems to work with any other smartmeter with dlms encryption. Will update in a few minutes

**Comment by ximex** [comment]
sry hat the wrong pr id before. the 8009 is correct

**Comment by pos-ei-don** [comment]
Hm, the code "external_components" does not work here,and i cannot find the error?!?

```
ERROR Error while reading config: Invalid YAML syntax:

while parsing a block collection
  in "/config/esphome/smartmeter-v3.yaml", line 14, column 3
expected <block end>, but found '?'
  in "/config/esphome/smartmeter-v3.yaml", line 30, column 3
```

Any idea?

**Comment by cococheaf** [comment]
So i got it perfectly working again with this yaml configuration.
Running on a ESP32DEV board with MBus Slave Click and Kaifa MA309M:

```yaml

esphome:
  name: smartmeter
  comment: "'NodeMCU ESP32 Dev' mit MikroE-MBUS-SlaveClick an Kaifa MA309M Stromzähler"
  friendly_name: Stromzähler

esp32:
  board: esp32dev

api:

ota:
 - platform: esphome
   password: "yourotasecret"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: w.x.y.z
    gateway: w.x.y.z
    subnet: w.x.y.z
    dns1: w.x.y.z
  ap:
    ssid: "yourfallbackssid"
    password: "yourwifipwd!"

mqtt:
  broker: w.x.y.z
  username: yourmqttuser
  password: yourmqttpwd
  id: mqtt_broker

captive_portal:

logger:
  # level: VERBOSE
  # tx_buffer_size: 1024

web_server:
  port: 80
  version: 2
  local: true

external_components:
  - source: github://SimonFischer04/esphome@dlms-meter
    components: [ dlms_meter ]

uart:
  rx_pin: GPIO33
  tx_pin: GPIO32
  baud_rate: 2400
  data_bits: 8
  stop_bits: 1
  rx_buffer_size: 2048
  id: mbus

dlms_meter:
  decryption_key: "yourencryptionkey"

sensor:
  - platform: dlms_meter
    voltage_l1:
      name: "smartmeter_voltage_l1"
    voltage_l2:
      name: "smartmeter_voltage_l2"
    voltage_l3:
      name: "smartmeter_voltage_l3"
    current_l1:
      name: "smartmeter_current_l1"
    current_l2:
      name: "smartmeter_current_l2"
    current_l3:
      name: "smartmeter_current_l3"
    active_power_plus:
      name: "smartmeter_active_power_plus"
    active_power_minus:
      name: "smartmeter_active_power_minus"
    active_energy_plus:
      name: "smartmeter_active_energy_plus"
    active_energy_minus:
      name: "smartmeter_active_energy_minus"
    reactive_energy_plus:
      name: "smartmeter_reactive_energy_plus"
    reactive_energy_minus:
      name: "smartmeter_reactive_energy_minus"

text_sensor:
  - platform: dlms_meter
    timestamp:
      name: "smartmeter_timestamp"

```
